export const GET_ORDER_DETAILS_REQUEST= 'GET_ORDER_DETAILS_REQUEST';
export const UPDATE_ORDER_DETAILS_REQUEST= 'UPDATE_ORDER_DETAILS_REQUEST';
export const SET_MODAL_STATUS_AND_ACTION_DATA = 'SET_MODAL_STATUS_AND_ACTION_DATA'